config/routes.rb
WWPP::Application.routes.draw do |map|
  resources :events
  resources :attendees
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :attendee
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  has_many :answers 
  belongs_to :event

  def answer_for(question)
    logger.info "question #{question.id}"
    @answer = self.answers.find(:first, :conditions => {:question_id => question.id})
    unless @answer
      @answer = self.answers.create(:answer => 0, :question_id=>question.id)
    end
    @answer
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :questions
  has_many :attendees, :order => "id DESC"
  attr_reader :questions_text

  def questions_text=(text)
    @qt = text.split(/\n/)
    self.questions.each do |qs|
      if(!@qt.include? qs.text)
        qs.destroy
      end
    end
    @qt.each do |text| 
      if (self.id && !Question.find_by_text(text) && !text.strip.empty?)
        @q = self.questions.create(:text => text)
        @q.save
        self.attendees.each do |attendee|
          ans = attendee.answers.create(:question_id => @q.id, :answer => 0)
          ans.save
        end
      elsif (!self.id)
        self.questions.build(:text => text)
      end
    end
  end
  
  def getQuestionsText
    @result = ""
    self.questions.each do |q|
      @result += q.text +
      "\n"
    end
    @result
  end
  
  def get_best_match 
    g = []
    self.questions.each do |q|
      count = 0
      q.answers.each do |ans|
        if ans.answer == 3 # not sure about weight. Now, OK = 3 points, not sure 2, "X" and "-" zero
          count += 2
        elsif ans.answer == 2
          count += 1
        elsif ans.answer == 1
          count -= 2
        end
      end
      g << [q.id,count]
    end
    g.sort! {|e1,e2| e2[1]-e1[1]}
    place = []
    score = g[0][1]
    d = []
    g.each do |e|
      if e[1] != score
        place << d
        d = [e[0]]
        score = e[1]
      else
        d << e[0]
      end
    end
    place << d
    answer = {}
    place.each_with_index do |e,i|
      e.each { |j| answer["#{j}"] = i}
    end
    answer
  end
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, :order => "attendee_id desc"
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

  def create
    @attendee = Attendee.new(params[:attendee])
    @attendee.save
    redirect_to :action=>:edit, :id=>@attendee.id
  end

  def edit
    @attendee = Attendee.find(params[:id])
    @event = Event.find(@attendee.event.id)
  end
  
  def update
    @attendee = Attendee.find(params[:id])
    respond_to do |format|
      answers = params[:attendee][:answers]
     
      if Answer.update(answers.keys, answers.values)#@attendee.update_attributes(params[:attendee])
        format.html { redirect_to(@attendee.event, :notice => 'Attendance was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @attendee.errors, :status => :unprocessable_entity }
      end
    end
    
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])
    @signs = ['-','X','△','O']
    @best = @event.get_best_match
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    @questions_text = @event.getQuestionsText
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
  def sign(answer)
    signs = ['-','X','△','O']
    signs[answer]
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/attendees/edit.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>
<%= form_for @attendee do |f| %>
<p>Questions:</p>
<table class='event_table'>
  <tr>
    <th>&nbsp;</th>
  <% @event.attendees.each do |t| %>
    <th><%= h t.name %></th>
  <% end %>
  </tr>
  <% @event.questions.each do |q| %>
  <tr>
    <td class="question_texts"><%= h q.text %></td>
    <% @event.attendees.each do |t| %>
      <% if t.id == @attendee.id %>
      <% @ans = t.answer_for q %>
        <td>
        <%= fields_for "attendee[answers][]", @ans do |answer_f| %>
        <%= answer_f.select :answer,  
        options_for_select([['-', 0], 
                          ['X',1], 
                          ['△',2],
                          ['O',3]], @ans.answer) %>
        <% end %>
        </td>
        
      <% else %>
    <td><%= sign (t.answer_for q).answer %></td>
      <% end %>
      <% end %>
  </tr>
  <% end %>
</table>
<%= f.submit  "Submit" %>
<% end %>

<%= link_to 'Cancel', (@event) %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label "questions" %><br />
    <%= f.text_area :questions_text, :value => @questions_text%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Questions</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.description %></td>
    <td><%= event.questions %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>Create new event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p class="event_title">
  <%= @event.title %>
</p>

<p class="event_desc">
  <%= @event.description %>
</p>

<table class="event_table">
  <tr>
    <th>&nbsp;</th>
  <% for t in @event.attendees %>
    <th><%= link_to t.name, edit_attendee_path(t) %></th>
  <% end %>
  </tr>
  <% @event.questions.each do |q| %>
  <% 
  if @best["#{q.id}"] == 0
    @class = "selected"
  else
    @class = ""
  end
  %>
  <tr class="<%= @class %>">
    <td class="question_texts"> <%= q.text %></td>
    <% for answer in q.answers %>
    
    <td><%=  @signs[answer.answer] %></td>
    <% end %>
  </tr>
  <% end %>
</table>

<div>
   <%= form_for Attendee.new  do |f| %>
   <%= f.label :name, "Your name:" %>
   <%= f.text_field :name %>
   <%= f.hidden_field :event_id, {:value=>@event.id} %>
   <%= f.submit  "Join" %>
<% end %>
</div>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WWPP</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id='main'>
    <%= yield %>
  </div>
</body>
</html>